version: "3.1"
services:
  kibana:
    image: "kibana:7.16.2"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
  elasticsearch:
    image: "elasticsearch:7.16.2"
    ports:
      - "127.0.0.1:9300:9300"
      - "127.0.0.1:9200:9200"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
volumes:
  elasticdata:
